sudo: false
language: bash

notifications:
  email:
    recipients:
    - info@mozilla.cz
    on_success: change
    on_failure: always

env:
 - DIR=browser
 - DIR=mail
 - DIR=mobile
 - DIR=suite

script:
 - bash ./check.sh $DIR

